### ISSUE TITLE
TODO for Shell Task and ContainerTask

### ISSUE THREAD

**Issue by djarecka** [nipype/pydra#141]
There are some issues tak don't have to be fixed right away, but should be done soon:
(will be updated)

- [x] cmdline for Shell: doesn't make sense for tasks with splitter

- [x] inputs for Containers: 
      - checking if has image and it's proper image, raising exceptions; 
      - bindings: allowing for tuple (not only list), tuple should be 3 or 2 elements (without `ro`)
      - checking if the local directory exists

- [x] adding an option to `Task` that converts it to the `DockerTask`: see @satra comments in #144 

- [x] provide option to have position for arguments

**Comment by satra** [comment]
is this now taken care of?

**Comment by djarecka** [comment]
not all

**Comment by djarecka** [comment]
addressed in #184, #186
